services:
  # ------------------------------------------------------------------ #
  localstack:
    image: localstack/localstack:3          # Local AWS mock (S3/SQS/Dynamo)
    ports:
      - "4566:4566"                         # single edge port for every API
    environment:
      - SERVICES=s3,sqs,dynamodb            # only what we need
      - LS_LOG=warn                         # quieter output
    volumes:
      - ./localstack-data:/var/lib/localstack   # persist data between runs

  # ------------------------------------------------------------------ #
  runner:
    build:
      context: .
      dockerfile: hc_services/runner/Dockerfile   # service Dockerfile
    environment:
      # Celery → SQS (LocalStack)
      - CELERY_BROKER_URL=sqs://
      - CELERY_BROKER_TRANSPORT_OPTIONS={"region":"eu-west-2","queue_name_prefix":"","visibility_timeout":30}
      # dummy AWS creds for local / Moto runs
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
      # point boto3 at LocalStack instead of AWS
      - AWS_ENDPOINT_URL=http://localstack:4566

      # same constants the code imports from hc_services.runner.constants
      - ARTIFACT_BUCKET=hc-artifacts
      - RUNS_TABLE=hc-runs
      - QUEUE_NAME=hc-artifacts-queue
    volumes:
      - .:/app                    # mount whole repo for hot-reload
    ports:
      - "8000:8000"               # expose Flask
    depends_on:
      - localstack

  # ------------------------------------------------------------------ #
  worker:
    build:
      context: .
      dockerfile: hc_services/runner/Dockerfile
    command:
      [
        "celery",
        "-A",
        "hc_services.runner.tasks",   # full module path
        "worker",
        "--loglevel=info"
      ]
    environment:
      - CELERY_BROKER_URL=sqs://
      - CELERY_BROKER_TRANSPORT_OPTIONS={"region":"eu-west-2","queue_name_prefix":"","visibility_timeout":30}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
      - AWS_ENDPOINT_URL=http://localstack:4566   # hit LocalStack

      # keep env-vars in sync with runner
      - ARTIFACT_BUCKET=hc-artifacts
      - RUNS_TABLE=hc-runs
      - QUEUE_NAME=hc-artifacts-queue
    volumes:
      - .:/app                    # hot-reload worker code
    depends_on:
      - localstack
      - runner                    # start once API image exists
